name: Java CI
on:
  push: {}
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  java_ci:
    name: Java CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 16]
      fail-fast: false
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: 📚 Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1.1.1
        with:
          version: ${{ matrix.jdk }}
          architecture: x64

      - name: 📤 Load Cache
        uses: actions/cache@v3.0.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: ✔ Test with Maven
        run: mvn test -fae --no-transfer-progress
